//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figaro.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Figaro.Utilities.Resources.CommandResources", typeof(CommandResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abort.
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addalias.
        /// </summary>
        internal static string addalias {
            get {
                return ResourceManager.GetString("addalias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addindex.
        /// </summary>
        internal static string addindex {
            get {
                return ResourceManager.GetString("addindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit.
        /// </summary>
        internal static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compactcontainer.
        /// </summary>
        internal static string compactcontainer {
            get {
                return ResourceManager.GetString("compactcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contextquery.
        /// </summary>
        internal static string contextquery {
            get {
                return ResourceManager.GetString("contextquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cquery.
        /// </summary>
        internal static string cquery {
            get {
                return ResourceManager.GetString("cquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createcontainer.
        /// </summary>
        internal static string createcontainer {
            get {
                return ResourceManager.GetString("createcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delindex.
        /// </summary>
        internal static string delindex {
            get {
                return ResourceManager.GetString("delindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo.
        /// </summary>
        internal static string echo {
            get {
                return ResourceManager.GetString("echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getdocuments.
        /// </summary>
        internal static string getdocuments {
            get {
                return ResourceManager.GetString("getdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getmetadata.
        /// </summary>
        internal static string getmetadata {
            get {
                return ResourceManager.GetString("getmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listindexes.
        /// </summary>
        internal static string listindexes {
            get {
                return ResourceManager.GetString("listindexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupedgeindex.
        /// </summary>
        internal static string lookupedgeindex {
            get {
                return ResourceManager.GetString("lookupedgeindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupindex.
        /// </summary>
        internal static string lookupindex {
            get {
                return ResourceManager.GetString("lookupindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupstats.
        /// </summary>
        internal static string lookupstats {
            get {
                return ResourceManager.GetString("lookupstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opencontainer.
        /// </summary>
        internal static string opencontainer {
            get {
                return ResourceManager.GetString("opencontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preload.
        /// </summary>
        internal static string preload {
            get {
                return ResourceManager.GetString("preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prepare.
        /// </summary>
        internal static string prepare {
            get {
                return ResourceManager.GetString("prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to putdocument.
        /// </summary>
        internal static string putdocument {
            get {
                return ResourceManager.GetString("putdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to putdocuments.
        /// </summary>
        internal static string putdocuments {
            get {
                return ResourceManager.GetString("putdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query.
        /// </summary>
        internal static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queryplan.
        /// </summary>
        internal static string queryplan {
            get {
                return ResourceManager.GetString("queryplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quit.
        /// </summary>
        internal static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reindexcontainer.
        /// </summary>
        internal static string reindexcontainer {
            get {
                return ResourceManager.GetString("reindexcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removealias.
        /// </summary>
        internal static string removealias {
            get {
                return ResourceManager.GetString("removealias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removecontainer.
        /// </summary>
        internal static string removecontainer {
            get {
                return ResourceManager.GetString("removecontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removedocument.
        /// </summary>
        internal static string removedocument {
            get {
                return ResourceManager.GetString("removedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setautoindexing.
        /// </summary>
        internal static string setautoindexing {
            get {
                return ResourceManager.GetString("setautoindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setbaseuri.
        /// </summary>
        internal static string setbaseuri {
            get {
                return ResourceManager.GetString("setbaseuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setignore.
        /// </summary>
        internal static string setignore {
            get {
                return ResourceManager.GetString("setignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setlazy.
        /// </summary>
        internal static string setlazy {
            get {
                return ResourceManager.GetString("setlazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setmetadata.
        /// </summary>
        internal static string setmetadata {
            get {
                return ResourceManager.GetString("setmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setnamespace.
        /// </summary>
        internal static string setnamespace {
            get {
                return ResourceManager.GetString("setnamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setprojection.
        /// </summary>
        internal static string setprojection {
            get {
                return ResourceManager.GetString("setprojection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setquerytimeout.
        /// </summary>
        internal static string setquerytimeout {
            get {
                return ResourceManager.GetString("setquerytimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setvariable.
        /// </summary>
        internal static string setvariable {
            get {
                return ResourceManager.GetString("setvariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setverbose.
        /// </summary>
        internal static string setverbose {
            get {
                return ResourceManager.GetString("setverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        internal static string sync {
            get {
                return ResourceManager.GetString("sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction.
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgradecontainer.
        /// </summary>
        internal static string upgradecontainer {
            get {
                return ResourceManager.GetString("upgradecontainer", resourceCulture);
            }
        }
    }
}
