//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figaro.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandSummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandSummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Figaro.Utilities.Resources.CommandSummaryResources", typeof(CommandSummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aborts the current transaction.
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adds an alias to the default container.
        /// </summary>
        internal static string addalias {
            get {
                return ResourceManager.GetString("addalias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add an index to the default container.
        /// </summary>
        internal static string addindex {
            get {
                return ResourceManager.GetString("addindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close a container currently open by the shell..
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commits the current transaction &amp; starts a new one.
        /// </summary>
        internal static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compact a container to shrink its size.
        /// </summary>
        internal static string compactcontainer {
            get {
                return ResourceManager.GetString("compactcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute a query expression against the last results returned.
        /// </summary>
        internal static string contextquery {
            get {
                return ResourceManager.GetString("contextquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute a query expression against the default container.
        /// </summary>
        internal static string cquery {
            get {
                return ResourceManager.GetString("cquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creates a new container, which becomes the default.
        /// </summary>
        internal static string createcontainer {
            get {
                return ResourceManager.GetString("createcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete an index from the default container.
        /// </summary>
        internal static string delindex {
            get {
                return ResourceManager.GetString("delindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo to output.
        /// </summary>
        internal static string echo {
            get {
                return ResourceManager.GetString("echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gets document(s) by name from the default container.
        /// </summary>
        internal static string getdocuments {
            get {
                return ResourceManager.GetString("getdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get metadata from the default document.
        /// </summary>
        internal static string getmetadata {
            get {
                return ResourceManager.GetString("getmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prints command help information.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get info on a default container.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list all indexes in the default container.
        /// </summary>
        internal static string listindexes {
            get {
                return ResourceManager.GetString("listindexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performs an edge index lookup in the default container.
        /// </summary>
        internal static string lookupedgeindex {
            get {
                return ResourceManager.GetString("lookupedgeindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performs an index lookup in the default container.
        /// </summary>
        internal static string lookupindex {
            get {
                return ResourceManager.GetString("lookupindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to looks up index statistics on the default container.
        /// </summary>
        internal static string lookupstats {
            get {
                return ResourceManager.GetString("lookupstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opens a container and uses it as the default container.
        /// </summary>
        internal static string opencontainer {
            get {
                return ResourceManager.GetString("opencontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pre-loads (opens) a container.
        /// </summary>
        internal static string preload {
            get {
                return ResourceManager.GetString("preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prepare a query expression as the default pre-parsed query.
        /// </summary>
        internal static string prepare {
            get {
                return ResourceManager.GetString("prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print most recent results, optionally to a file.
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert a document into the default container.
        /// </summary>
        internal static string putdocument {
            get {
                return ResourceManager.GetString("putdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert documents from a directory into the current container.
        /// </summary>
        internal static string putdocuments {
            get {
                return ResourceManager.GetString("putdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to execute the given expression or default pre-parsed query.
        /// </summary>
        internal static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prints the query plan for the given query expression.
        /// </summary>
        internal static string queryplan {
            get {
                return ResourceManager.GetString("queryplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re-index a container, optionally changing its index type.
        /// </summary>
        internal static string reindexcontainer {
            get {
                return ResourceManager.GetString("reindexcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove an alias from the default container.
        /// </summary>
        internal static string removealias {
            get {
                return ResourceManager.GetString("removealias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove a container.
        /// </summary>
        internal static string removecontainer {
            get {
                return ResourceManager.GetString("removecontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove a document from the default container.
        /// </summary>
        internal static string removedocument {
            get {
                return ResourceManager.GetString("removedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run the given file as a dbxml script.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set the auto-indexing state of the default container.
        /// </summary>
        internal static string setautoindexing {
            get {
                return ResourceManager.GetString("setautoindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sets the base URI in the default context.
        /// </summary>
        internal static string setbaseuri {
            get {
                return ResourceManager.GetString("setbaseuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tell the dbxml shell to ignore script errors.
        /// </summary>
        internal static string setignore {
            get {
                return ResourceManager.GetString("setignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enables/disables lazy evaluation in the default context.
        /// </summary>
        internal static string setlazy {
            get {
                return ResourceManager.GetString("setlazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a metadata item on the named document.
        /// </summary>
        internal static string setmetadata {
            get {
                return ResourceManager.GetString("setmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a prefix-&gt;namespace binding in the default context.
        /// </summary>
        internal static string setnamespace {
            get {
                return ResourceManager.GetString("setnamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enables/disables document projection optimization.
        /// </summary>
        internal static string setprojection {
            get {
                return ResourceManager.GetString("setprojection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a query timeout in seconds in the default context.
        /// </summary>
        internal static string setquerytimeout {
            get {
                return ResourceManager.GetString("setquerytimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a variable to the specified type in the default context.
        /// </summary>
        internal static string settypedvariable {
            get {
                return ResourceManager.GetString("settypedvariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set a variable in the default context.
        /// </summary>
        internal static string setvariable {
            get {
                return ResourceManager.GetString("setvariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set verbosity of the dbxml shell.
        /// </summary>
        internal static string setverbose {
            get {
                return ResourceManager.GetString("setverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync current container to disk.
        /// </summary>
        internal static string sync {
            get {
                return ResourceManager.GetString("sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrap a command in a timer.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a transaction for all subsequent operations to use.
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade a container to the current BDB container format.
        /// </summary>
        internal static string upgradecontainer {
            get {
                return ResourceManager.GetString("upgradecontainer", resourceCulture);
            }
        }
    }
}
