//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figaro.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandUsageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandUsageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Figaro.Utilities.Resources.CommandUsageResources", typeof(CommandUsageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abort.
        /// </summary>
        internal static string abort {
            get {
                return ResourceManager.GetString("abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addAlias &lt;alias&gt; [containerName].
        /// </summary>
        internal static string addalias {
            get {
                return ResourceManager.GetString("addalias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addIndex [&lt;nodeNamespaceUri&gt; &lt;nodeName&gt;] &lt;indexDescription&gt;.
        /// </summary>
        internal static string addindex {
            get {
                return ResourceManager.GetString("addindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close [containerName].
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit.
        /// </summary>
        internal static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compactContainer &lt;containerName&gt;.
        /// </summary>
        internal static string compactcontainer {
            get {
                return ResourceManager.GetString("compactcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contextQuery &lt;queryExpression&gt;.
        /// </summary>
        internal static string contextquery {
            get {
                return ResourceManager.GetString("contextquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cquery &lt;queryExpression&gt;.
        /// </summary>
        internal static string cquery {
            get {
                return ResourceManager.GetString("cquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createContainer &lt;containerName&gt; [n|in|d|id] [[no]validate].
        /// </summary>
        internal static string createcontainer {
            get {
                return ResourceManager.GetString("createcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delIndex [&lt;nodeNamespaceUri&gt; &lt;nodeName&gt;] &lt;indexDescription&gt;.
        /// </summary>
        internal static string delindex {
            get {
                return ResourceManager.GetString("delindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to echo [text].
        /// </summary>
        internal static string echo {
            get {
                return ResourceManager.GetString("echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getDocuments [&lt;docName&gt;].
        /// </summary>
        internal static string getdocuments {
            get {
                return ResourceManager.GetString("getdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMetaData &lt;docName&gt; [&lt;metaDataUri&gt; &lt;metaDataName&gt;].
        /// </summary>
        internal static string getmetadata {
            get {
                return ResourceManager.GetString("getmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help [command].
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info [preload].
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listIndexes.
        /// </summary>
        internal static string listindexes {
            get {
                return ResourceManager.GetString("listindexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupEdgeIndex &lt;indexDescription&gt; &lt;namespaceUri&gt; &lt;nodeName&gt;
        ///        &lt;parentNamespaceUri&gt; &lt;parentNodeName&gt; [[&lt;operation&gt;] &lt;value&gt;].
        /// </summary>
        internal static string lookupedgeindex {
            get {
                return ResourceManager.GetString("lookupedgeindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupIndex &lt;indexDescription&gt; &lt;namespaceUri&gt; &lt;nodeName&gt;
        ///        [[&lt;operation&gt;] &lt;value&gt;].
        /// </summary>
        internal static string lookupindex {
            get {
                return ResourceManager.GetString("lookupindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lookupStats &lt;indexDescription&gt; &lt;namespaceUri&gt; &lt;nodeName&gt;
        ///        [&lt;parentNodeNamespaceUri&gt; &lt;parentNodeName&gt; &lt;value&gt; lookupStats &lt;indexDescription&gt; &lt;namespaceUri&gt; &lt;nodeName&gt;
        ///        [&lt;parentNodeNamespaceUri&gt; &lt;parentNodeName&gt; &lt;value&gt; ].
        /// </summary>
        internal static string lookupstats {
            get {
                return ResourceManager.GetString("lookupstats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opencontainer &lt;container&gt; [[no]validate].
        /// </summary>
        internal static string opencontainer {
            get {
                return ResourceManager.GetString("opencontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preload &lt;container&gt;.
        /// </summary>
        internal static string preload {
            get {
                return ResourceManager.GetString("preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prepare &lt;queryExpression&gt;.
        /// </summary>
        internal static string prepare {
            get {
                return ResourceManager.GetString("prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print | printNames [n &lt;number&gt;] [pathToFile].
        /// </summary>
        internal static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to putDocument &lt;string&gt; [namePrefix] [f|s|q].
        /// </summary>
        internal static string putdocument {
            get {
                return ResourceManager.GetString("putdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to putDocuments &lt;path&gt; [searchPattern].
        /// </summary>
        internal static string putdocuments {
            get {
                return ResourceManager.GetString("putdocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query [queryExpression].
        /// </summary>
        internal static string query {
            get {
                return ResourceManager.GetString("query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queryPlan &lt;queryExpression&gt; [pathToFile].
        /// </summary>
        internal static string queryplan {
            get {
                return ResourceManager.GetString("queryplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reindexContainer &lt;containerName&gt; &lt;d|n&gt;.
        /// </summary>
        internal static string reindexcontainer {
            get {
                return ResourceManager.GetString("reindexcontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeAlias &lt;alias&gt;.
        /// </summary>
        internal static string removealias {
            get {
                return ResourceManager.GetString("removealias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeContainer &lt;containerName&gt;.
        /// </summary>
        internal static string removecontainer {
            get {
                return ResourceManager.GetString("removecontainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeDocument &lt;docName&gt;.
        /// </summary>
        internal static string removedocument {
            get {
                return ResourceManager.GetString("removedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run &lt;scriptFile&gt;.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setAutoIndexing &lt;on|off&gt;.
        /// </summary>
        internal static string setautoindexing {
            get {
                return ResourceManager.GetString("setautoindexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setBaseUri [uri].
        /// </summary>
        internal static string setbaseuri {
            get {
                return ResourceManager.GetString("setbaseuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setIgnore &lt;on|off&gt;.
        /// </summary>
        internal static string setignore {
            get {
                return ResourceManager.GetString("setignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setLazy &lt;on|off&gt;.
        /// </summary>
        internal static string setlazy {
            get {
                return ResourceManager.GetString("setlazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setMetaData &lt;docName&gt; &lt;metaDataUri&gt; &lt;metaDataName&gt;
        ///        &lt;metaDataValue&gt;.
        /// </summary>
        internal static string setmetadata {
            get {
                return ResourceManager.GetString("setmetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setNamespace &lt;prefix&gt; &lt;namespaceUri&gt;.
        /// </summary>
        internal static string setnamespace {
            get {
                return ResourceManager.GetString("setnamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setProjection &lt;on|off&gt;.
        /// </summary>
        internal static string setprojection {
            get {
                return ResourceManager.GetString("setprojection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setQueryTimeout &lt;seconds&gt;.
        /// </summary>
        internal static string setquerytimeout {
            get {
                return ResourceManager.GetString("setquerytimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setVariable &lt;varName&gt; [&lt;value&gt; (&lt;value&gt;...)].
        /// </summary>
        internal static string setvariable {
            get {
                return ResourceManager.GetString("setvariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setVerbose &lt;level&gt; &lt;category&gt;.
        /// </summary>
        internal static string setverbose {
            get {
                return ResourceManager.GetString("setverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        internal static string sync {
            get {
                return ResourceManager.GetString("sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time command [args].
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction.
        /// </summary>
        internal static string transaction {
            get {
                return ResourceManager.GetString("transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgradeContainer &lt;containerName&gt;.
        /// </summary>
        internal static string upgradecontainer {
            get {
                return ResourceManager.GetString("upgradecontainer", resourceCulture);
            }
        }
    }
}
